runtime: nodejs22

instance_class: F2

handlers:
  - url: /
    static_files: greenthumb-app/browser/index.html
    upload: greenthumb-app/browser/index.html

  - url: /
    static_dir: greenthumb-app/browser
